"""Initial migration

Revision ID: a2807b443c4c
Revises: 
Create Date: 2026-05-05 00:39:30.852803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2807b443c4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('breeding_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=False),
    sa.Column('feed_type', sa.String(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.Column('date_administered', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tasks')
    op.drop_table('health_records')
    op.drop_index('ix_farmers_email', table_name='farmers')
    op.drop_table('farmers')
    op.add_column('cattle', sa.Column('tag_id', sa.String(), nullable=False))
    op.add_column('cattle', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='cattlegender'), nullable=False))
    op.add_column('cattle', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('cattle', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('cattle', sa.Column('farm_id', sa.UUID(), nullable=False))
    op.add_column('cattle', sa.Column('parent_mother_id', sa.UUID(), nullable=True))
    op.add_column('cattle', sa.Column('parent_father_id', sa.UUID(), nullable=True))
    op.add_column('cattle', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cattle', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cattle', sa.Column('qr_code_url', sa.String(), nullable=True))
    op.alter_column('cattle', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('cattle', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cattle', 'breed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cattle', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE', 'SOLD', 'DECEASED', name='cattlestatus'),
               existing_nullable=True)
    op.drop_index('ix_cattle_id', table_name='cattle')
    op.create_index(op.f('ix_cattle_tag_id'), 'cattle', ['tag_id'], unique=True)
    op.drop_constraint('cattle_owner_id_fkey', 'cattle', type_='foreignkey')
    op.create_foreign_key(None, 'cattle', 'farms', ['farm_id'], ['id'])
    op.create_foreign_key(None, 'cattle', 'cattle', ['parent_father_id'], ['id'])
    op.create_foreign_key(None, 'cattle', 'cattle', ['parent_mother_id'], ['id'])
    op.drop_column('cattle', 'pregnant')
    op.drop_column('cattle', 'age')
    op.drop_column('cattle', 'owner_id')
    op.drop_column('cattle', 'image_url')
    op.alter_column('farms', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('farms', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('farms', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('farms_owner_id_fkey', 'farms', type_='foreignkey')
    op.create_foreign_key(None, 'farms', 'users', ['owner_id'], ['id'])
    op.drop_column('farms', 'updated_at')
    op.add_column('health_logs', sa.Column('diagnosis', sa.String(), nullable=True))
    op.add_column('health_logs', sa.Column('temperature', sa.Float(), nullable=True))
    op.alter_column('health_logs', 'cattle_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('health_logs', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'health_logs', 'cattle', ['cattle_id'], ['id'])
    op.drop_column('health_logs', 'type')
    op.drop_column('health_logs', 'updated_at')
    op.drop_column('health_logs', 'status')
    op.drop_column('health_logs', 'date')
    op.add_column('milk_logs', sa.Column('quantity_liters', sa.Float(), nullable=False))
    op.add_column('milk_logs', sa.Column('fat_content', sa.Float(), nullable=True))
    op.add_column('milk_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('milk_logs', 'cattle_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('milk_logs', 'session',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('milk_logs', 'yield_liters')
    op.drop_column('milk_logs', 'date')
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'en'::text"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_constraint('users_id_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_id_fkey', 'users', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'is_superuser')
    op.add_column('milk_logs', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('milk_logs', sa.Column('yield_liters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('milk_logs', 'session',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('milk_logs', 'cattle_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('milk_logs', 'created_at')
    op.drop_column('milk_logs', 'fat_content')
    op.drop_column('milk_logs', 'quantity_liters')
    op.add_column('health_logs', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('health_logs', sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True))
    op.add_column('health_logs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('health_logs', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'health_logs', type_='foreignkey')
    op.alter_column('health_logs', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('health_logs', 'cattle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('health_logs', 'temperature')
    op.drop_column('health_logs', 'diagnosis')
    op.add_column('farms', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.create_foreign_key('farms_owner_id_fkey', 'farms', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('farms', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('farms', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('farms', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('cattle', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cattle', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('cattle', sa.Column('age', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cattle', sa.Column('pregnant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cattle', type_='foreignkey')
    op.drop_constraint(None, 'cattle', type_='foreignkey')
    op.drop_constraint(None, 'cattle', type_='foreignkey')
    op.create_foreign_key('cattle_owner_id_fkey', 'cattle', 'farmers', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_cattle_tag_id'), table_name='cattle')
    op.create_index('ix_cattle_id', 'cattle', ['id'], unique=False)
    op.alter_column('cattle', 'status',
               existing_type=sa.Enum('ACTIVE', 'SOLD', 'DECEASED', name='cattlestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('cattle', 'breed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cattle', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cattle', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('cattle', 'qr_code_url')
    op.drop_column('cattle', 'updated_at')
    op.drop_column('cattle', 'created_at')
    op.drop_column('cattle', 'parent_father_id')
    op.drop_column('cattle', 'parent_mother_id')
    op.drop_column('cattle', 'farm_id')
    op.drop_column('cattle', 'weight')
    op.drop_column('cattle', 'date_of_birth')
    op.drop_column('cattle', 'gender')
    op.drop_column('cattle', 'tag_id')
    op.create_table('farmers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('farm_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language_preference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='farmers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_farmers_email', 'farmers', ['email'], unique=True)
    op.create_table('health_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cattle_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('treatment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('vet_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], name='health_records_cattle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_records_pkey')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['farmers.id'], name='tasks_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    op.drop_table('vaccinations')
    op.drop_table('medicines')
    op.drop_table('feed_logs')
    op.drop_table('documents')
    op.drop_table('breeding_logs')
    op.drop_table('alerts')
    # ### end Alembic commands ###
